language: php

sudo: false

php:
  - "7.0"

matrix:
  include:
    - php: "7.2"
      env: COVERAGE="NO" TYPO3_VERSION="dev-master"
    - php: "7.0"
      env: COVERAGE="NO" TYPO3_VERSION="^8.7"
    - php: "7.1"
      env: COVERAGE="NO" TYPO3_VERSION="^8.7"
    - php: "7.2"
      env: COVERAGE="YES" TYPO3_VERSION="^8.7"
    - php: "7.2"
      env: COVERAGE="NO" TYPO3_VERSION="^9"
    - php: "7.3"
      env: COVERAGE="NO" TYPO3_VERSION="^9"
    - php: "7.4"
      env: COVERAGE="NO" TYPO3_VERSION="^9"
  allow_failures:
    - env: COVERAGE="NO" TYPO3_VERSION="dev-master"

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - mkdir -p build/logs
  - export TYPO3_PATH_WEB=$PWD/build/web

install:
  - composer require "typo3/cms-core:$TYPO3_VERSION"

script: if [[ "$COVERAGE" != "NO" ]]; then ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml; else ./vendor/bin/phpunit; fi

after_script:
  - ln -s Classes src
  - if [[ "$COVERAGE" != "NO" ]]; then ./vendor/bin/coveralls; fi
