language: php
php:
  - 5.3
  - 5.4

env:
  - DB=mysql

before_script:
  - rm -rf *
  - git clone https://github.com/FluidTYPO3/TYPO3-Travis-Integration.git build-environment
  - source build-environment/install-helper.sh
  - git clone https://github.com/FluidTYPO3/TYPO3v4-Core.git --recurse-submodules build-environment/typo3 --depth 50
  - git clone https://github.com/FluidTYPO3/Introduction.git build-environment/Introduction
  - mkdir fileadmin
  - mkdir uploads
  - mv build-environment/typo3/* ./
# local init
  - rm -rf $PWD/typo3conf/ext/vhs
  - git clone https://github.com/FluidTYPO3/vhs.git typo3conf/ext/vhs --depth 50
  - rm phpunit.xml
  - cp $PWD/typo3conf/ext/vhs/Tests/phpunit.xml $PWD/phpunit.xml
# continue install
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Database/introduction.sql; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/dbimport/cache_tables.sql; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/dbimport/cli_users.sql; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/dbimport/phpunit.sql; fi

script:
  - php $PWD/typo3/cli_dispatch.phpsh phpunit -c phpunit.xml
